DROP USER C##DBManager CASCADE;
DROP USER C##employee CASCADE;
DROP USER C##usoffpass CASCADE;
DROP USER C##usonpass CASCADE;
--USERS CREATION
CREATE USER C##DBManager IDENTIFIED BY dbmpass;
CREATE USER C##employee IDENTIFIED BY empass;
CREATE USER C##usoffpass IDENTIFIED BY usoffpass; --Parental controll off
CREATE USER C##usonpass IDENTIFIED BY utonpass; --Parental controll on
--USERS'S PRIVILEGES
GRANT ALL PRIVILEGES TO C##DBManager;

GRANT CREATE SESSION TO C##DBManager;
GRANT CREATE SESSION TO C##employee;
GRANT CREATE SESSION TO C##usoffpass;
GRANT CREATE SESSION TO C##usonpass;

GRANT EXECUTE ON SUBSCRIPTION TO C##usoffpass;
GRANT EXECUTE ON REMOVE_PLAYLIST TO C##usoffpass;
GRANT EXECUTE ON ADD_CONTENT_TO_PLAYLIST TO C##usoffpass;
GRANT EXECUTE ON DELETE_CONTENT_FROM_PLAYLIST TO C##usoffpass;
GRANT EXECUTE ON ADD_REVIEW TO C##usoffpass;
GRANT EXECUTE ON RENEW_SUBSCRIPTION TO C##usoffpass;
GRANT EXECUTE ON ADD_PAYMENT_METHOD TO C##usoffpass;
GRANT EXECUTE ON REMOVE_DEVICE TO C##usoffpass;
GRANT INSERT ON FRIEND_OF TO C##usoffpass;
GRANT INSERT ON PROFILE TO C##usoffpass;
GRANT INSERT ON CONNECTED_DEVICES TO C##usoffpass;
GRANT INSERT ON PLAYLIST TO C##usoffpass;
GRANT SELECT ON SHOW_ALL_CONTENT TO C##usoffpass;
GRANT SELECT ON SHOW_MEMBERSHIPS TO C##usoffpass;

GRANT EXECUTE ON SUBSCRIPTION TO C##usonpass;
GRANT EXECUTE ON REMOVE_PLAYLIST TO C##usonpass;
GRANT EXECUTE ON ADD_CONTENT_TO_PLAYLIST TO C##usonpass;
GRANT EXECUTE ON DELETE_CONTENT_FROM_PLAYLIST TO C##usonpass;
GRANT EXECUTE ON ADD_REVIEW TO C##usonpass;
GRANT EXECUTE ON RENEW_SUBSCRIPTION TO C##usonpass;
GRANT EXECUTE ON ADD_PAYMENT_METHOD TO C##usonpass;
GRANT EXECUTE ON REMOVE_DEVICE TO C##usonpass;
GRANT INSERT ON FRIEND_OF TO C##usonpass;
GRANT INSERT ON PROFILE TO C##usonpass;
GRANT INSERT ON CONNECTED_DEVICES TO C##usonpass;
GRANT INSERT ON PLAYLIST TO C##usonpass;
GRANT SELECT ON SHOW_ALLOWED_CONTENT TO C##usonpass;
GRANT SELECT ON SHOW_MEMBERSHIPS TO C##usonpass;
--EMPLOYEE'S PRIVILEG
GRANT SELECT ON SHOW_ALL_CONTENT TO C##employee;
GRANT SELECT ON SHOW_MEMBERSHIPS TO C##employee;
GRANT EXECUTE ON ADD_CONTENT TO C##employee;
GRANT EXECUTE ON ADD_PARTICIPANT TO C##employee;
GRANT INSERT ON MEMBERSHIP TO C##employee;
GRANT UPDATE ON SERIES TO C##employee;
GRANT INSERT, UPDATE ON SEASON  TO C##employee;
GRANT INSERT ON EPISODE TO C##employee;


